### ISSUE TITLE
API down

### ISSUE THREAD

**Issue by azbang** [jedahan/collections-api#54]
Request `http://127.0.0.1:8080/random`
Response `Internal Server Error`
Error log:
```js
  xxx GET /random 500 354ms -
  TypeError: Cannot read property 'length' of undefined
      at Object.getRandom (C:\Users\azbang\collections-api\libs\getRandom.js:16:49)
      at getRandom.next (<anonymous>)
      at Object.dispatch (C:\Users\azbang\collections-api\node_modules\koa-router\lib\router.js:336:7)
      at dispatch.next (<anonymous>)
      at Object.mask (C:\Users\azbang\collections-api\node_modules\koa-json-mask\index.js:20:5)
      at mask.next (<anonymous>)
      at Object.serve (C:\Users\azbang\collections-api\node_modules\koa-static\index.js:43:7)
      at serve.next (<anonymous>)
      at Object.compress (C:\Users\azbang\collections-api\node_modules\koa-compress\index.js:42:5)
      at compress.next (<anonymous>)
```

**Comment by jedahan** [comment]
They changed a ton of things from the website, this needs to be rewritten.
